### PR TITLE
1.12 Support

### PR DESCRIPTION
**Pull request by DenielWorld**
Replace all entity stuff with actor for the new 1.12 update reee

### CODE REVIEW

**Comment by JackMD** [comment]
Thanks

**Comment by JackMD** [comment]
Daniel... Who tf told you that events were changed?

**Comment by DenielWorld** [comment]
The libs also have to be updated, as they cause most entity/actor related issues, but they weren't on this repo.

**Comment by DenielWorld** [comment]
Also, I keep up with every PMMP update :)

**Comment by JackMD** [comment]
This pr was completely useless.... Stupid of me to merge it..

**Comment by DenielWorld** [comment]
Oof

**Comment by DenielWorld** [comment]
Wait, it was just the protocol...

**Comment by JackMD** [comment]
Thats what I have been saying lmao

**Pull request merged**
