### PR TITLE
Add support for /key `<type>` all `<amount>`

### PR DESCRIPTION
**Pull request by Olybear9**
Add support for key all

### CODE REVIEW

**Comment by JackMD** [comment]
The key command is currently very over bloated and could be simplified even more. I plan on improving sometime today. Thanks for the pr tho. Every contribution counts.

**Comment by JackMD** [comment]
I will keep this open until I improve the current command.

**Comment by Olybear9** [comment]
Sounds good, 👍

**Comment by JackMD** [comment]
Im thinking of making a new command like /keyall instead of using the current key command.

**Comment by GiantQuartz** [comment]
That sounds better, to be honest. There are several reasons to create `keyall` instead a tag, in addition to maintainability, it would make it easier for the end user.

**Comment by JackMD** [comment]
Alright then. I would (hopefully) do it later today

**Comment by JackMD** [comment]
Done in [a440255](https://github.com/JackMD/MysteryCrate/commit/a4402559c655cf6a656146573ce1064d19db8876)

**Pull request closed without merging**
