### PR TITLE
Update EventListener.php

### PR DESCRIPTION
**Pull request by test474**

### CODE REVIEW

**Comment by JackMD** [comment]
what the fuck is this?

**Comment by esh123cookie** [comment]
Bro for 1.13 it crashes you I just fixed it

**Comment by JackMD** [comment]
There is no 1.13 official release. If it breaks on 1.13 unofficial either provided by me or other sources then I won't be updating anything. Wait of 1.13 official anyways this plugin won't be getting future updates anyways.

**Comment by esh123cookie** [comment]
Wait why not I love this plugin it's, really good. Why no more future updates? Also, I think this version of 1.13 which was crashing was provided by you.

**Pull request closed without merging**
